name: BuTils
main: wex\BuTils\BuTils
version: 0.0.3
api: 5.25.0
author: Wex
description: A build utility plugin that makes life easier for builders.
website: https://github.com/Xeww/BuTils

permissions:
  butils.command.butils:
    default: op

  butils.command.daylock:
    default: op
    description: "Allows the user to toggle day lock on/off"

  butils.command.flyspeed:
    default: op

  butils.command.noclip:
    default: op

  butils.command.nightvision:
    default: op

  butils.command.gamemode.creative:
    default: op
    description: "Allows the user to change to creative mode"

  butils.command.gamemode.survival:
    default: op
    description: "Allows the user to change to survival mode"

  butils.command.gamemode.adventure:
    default: op
    description: "Allows the user to change to adventure mode"

  butils.command.gamemode.spectator:
    default: op
    description: "Allows the user to change to spectator mode"
